### ISSUE TITLE
Change default image color

### ISSUE THREAD

**Issue by cpfarher** [filipdanic/react-wifi-indicator#2]
Hello, I follow your steps in order to change the image for some customized by me. I need to change de color from green to blue of the sign and I tried to modify like this:

`<WifiIndicator 
  statusImages={{
    EXCELLENT: 'something.svg',
    etc...
  }}
/>`

I think is a bug....
Thank you...

**Comment by filipdanic** [comment]
Hi @cpfarher, I just tested it and it seems to be working correctly. Here is a CodeSandbox file with 3 different types of image passing: https://codesandbox.io/s/react-wifi-indicator-wp5kb

Your snippet does not contain the `strength` prop. If you don’t actually provide `strength="EXCELLENT"` (or whatever other status), then nothing will show.

**Comment by cpfarher** [comment]
You are right!. I have a problem with an import. Thank you!
